'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class entityEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=entityEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Film() As DbSet(Of Film)
    Public Overridable Property Musteri() As DbSet(Of Musteri)
    Public Overridable Property Şehir() As DbSet(Of Şehir)
    Public Overridable Property Tarih() As DbSet(Of Tarih)
    Public Overridable Property Salon() As DbSet(Of Salon)

End Class
