'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Film
    Public Property FilmID As Integer
    Public Property FilmAdı As String

End Class
Partial Public Class Musteri
    Public Property UyeID As Integer
    Public Property Ad As String
    Public Property Soyad As String
    Public Property Mail As String
    Public Property parola As String
    Public Property telefon As String

End Class
Partial Public Class Salon
    Public Property ID As Integer
    Public Property SalonAD As String

End Class
Partial Public Class Şehir
    Public Property ID As Integer
    Public Property Ad As String

End Class
Partial Public Class Tarih
    Public Property ID As Integer
    Public Property Tarih1 As String

End Class
